name: time_tracker
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  flutter_riverpod: ^2.1.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  auto_route: ^5.0.2
  intl: ^0.17.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  auto_route_generator: ^5.0.3
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  dio_logger: ^4.0.8+8
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
flutter_intl:
  enabled: true
